name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug — this is the only required field.
      placeholder: A clear description of the bug...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Describe expected behavior...
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - high
        - medium
        - low
    validations:
      required: false

  # --- Agent Configuration (for Copilot coding agent) ---

  - type: dropdown
    id: agent
    attributes:
      label: Agent
      description: Which agent should handle this?
      options:
        - coder
        - planner
        - reviewer
    validations:
      required: false
  - type: textarea
    id: agent-instructions
    attributes:
      label: Agent Instructions
      description: Extra instructions for the AI agent working on this bug
      placeholder: "e.g. Check regression tests, look at recent commits..."
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional context
      description: Any extra context, screenshots, or logs
      placeholder: Optional...
